### ISSUE TITLE
npm run build throws error

### ISSUE THREAD

**Issue by krzysztofnowak** [joshuacaron/generator-angular2-gulp-webpack#2]
Hi, 
dev script seems to be ok, but while generating dist I found an issue.

While calling `npm run build` script starts but after a moment I see in console this error:

```
ts-loader: Using typescript@1.7.5 and /Documents/rd_anuglar2-3/src/tsconfig.json
[14:32:40] Version: webpack 1.12.9

ERROR in ./src/app/app.ts
Module build failed: TypeError: undefined is not a function
    at ensureTypeScriptInstance (/Documents/rd_anuglar2-3/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/Documents/rd_anuglar2-3/node_modules/ts-loader/index.js:365:14)
[14:32:40] Finished 'webpack' after 1.06 s
```

**Comment by joshuacaron** [comment]
Hi, thanks for letting me know. I've updated the package and testing it and everything is working now. I also updated to the latest version of angular2.
